version: '3.7'


services:
  db:
    image: postgres:13.3
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5435:5432
#    environment:
#      POSTGRES_DATABASE: root
#      POSTGRES_USER: root
#      POSTGRES_PASSWORD: root
#      POSTGRES_ROOT_PASSWORD: root
  web:
    build: .
    command: python /usr/src/dm_rest/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/dm_rest
    ports:
      - 8000:8000
    depends_on:
      - db
volumes:
  postgres_data: