# Generated by Django 3.2.8 on 2022-06-04 17:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(inverse_match=True, message='уберите точку!', regex='\\.$')], verbose_name='Категория')),
                ('image', models.ImageField(upload_to='', verbose_name='image')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('whatsapp', models.CharField(blank=True, max_length=100, null=True, verbose_name='Whatsapp|Номер телефона')),
                ('telegram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram|URL')),
                ('number_main', models.CharField(blank=True, max_length=100, null=True, verbose_name='Главный номер телефона')),
                ('number_two', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='NewProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Новый продукт',
                'verbose_name_plural': 'Новый продукт',
            },
        ),
        migrations.CreateModel(
            name='Ordering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Фио')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('region', models.CharField(max_length=100, verbose_name='Область')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('basket', models.TextField(verbose_name='Корзина')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адресы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(inverse_match=True, message='уберите точку!', regex='\\.$')], verbose_name='Название')),
                ('image', models.ImageField(upload_to='', verbose_name='image')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.DecimalValidator(decimal_places=2, max_digits=8)], verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание')),
                ('are_available', models.BooleanField(default=True, verbose_name='имеется в наличии')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='Количество товара')),
                ('sale', models.IntegerField(blank=True, default=0, null=True, verbose_name='Скидка в процентах')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_detail', to='data.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('products', models.ManyToManyField(related_name='recommendations_detail', to='data.Product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'рекомендация',
                'verbose_name_plural': 'рекомендации',
            },
        ),
    ]
