# Generated by Django 3.2.8 on 2022-06-04 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewProduct',
        ),
    ]
