# Generated by Django 3.2.8 on 2022-06-06 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_delete_newproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('products', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='new_product', to='data.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Новый продукт',
                'verbose_name_plural': 'Новый продукт',
            },
        ),
    ]
