# Generated by Django 3.2.8 on 2022-06-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_newproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-name',), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='Черновик'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
