# Generated by Django 3.2.8 on 2022-06-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20220606_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slag',
            field=models.SlugField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
