# Generated by Django 3.2.8 on 2022-06-07 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_rename_slag_product_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Картинки товаров')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.product')),
            ],
            options={
                'verbose_name': 'Картинка товара',
                'verbose_name_plural': 'Картинки товаров',
            },
        ),
    ]
